---
- hosts: vm
  vars:
    worker_root: /home/ansible-worker/www
    nginx_avail: /etc/nginx/sites-available
    nginx_enabled: /etc/nginx/sites-enabled
  tasks:
    - name: create user
      become: yes
      ansible.builtin.user:
        name: ansible-worker

    - name: install git
      become: yes
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: copy keys
      become: yes
      ansible.builtin.copy:
        dest: ~/.ssh/
        src: ssh_keys/

    - name: clone repo
      become: yes
      ansible.builtin.git:
        repo: https://github.com/iphilka/stud-template
        dest: "{{worker_root}}"

    - name: install nginx
      become: yes
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: copy index.html
      become: yes
      ansible.builtin.copy:
        dest: "{{worker_root}}/index.html"
        src: index.html
        owner: ansible-worker
        group: ansible-worker

    - name: copy nginx conf
      become: yes
      ansible.builtin.copy:
        dest: "{{nginx_avail}}/ansible.iphilka.ru.conf"
        src: ansible.iphilka.ru.conf
        owner: root
        group: root
        mode: 0755

    - name: enable site
      become: yes
      file:
        src: "{{nginx_avail}}/ansible.iphilka.ru.conf"
        dest: "{{nginx_enabled}}/ansible.iphilka.ru.conf"
        state: link

    - name: disable default site
      become: yes
      file:
        path: "{{nginx_enabled}}/default"
        state: absent

    - name: restart nginx
      become: yes
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted

